export const VIEW_FOOT='VIEW_FOOT';
export const VIEW_LOADING='VIEW_LOADING';
export const UPDATE_HOME='UPDATE_HOME';
export const UPDATE_INTEGRAL='UPDATE_INTEGRAL';
export const UPDATE_DETAIL='UPDATE_DETAIL';
export const CHECK_USER='CHECK_USER';